# Generated by Django 4.2.28 on 2026-02-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('arrival', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
