# Generated by Django 4.2.28 on 2026-02-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='arrival',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author')},
        ),
    ]
